DEFAULT_PROVIDER = "openai"
DEFAULT_MAX_FILES = 50
DEFAULT_GENERATION_WORKERS = 4
DEFAULT_PLANNING_WORKERS = 4
DEFAULT_TIMEOUT = 120.0
DEFAULT_LANGUAGE = "auto"

DEFAULT_LLM_MAX_RETRIES = 5
DEFAULT_LLM_INITIAL_BACKOFF = 10.0
DEFAULT_LLM_MAX_BACKOFF = 120.0
DEFAULT_LLM_BACKOFF_JITTER = 0.2

ALLOWED_LANGUAGES = frozenset({"auto", "python", "r", "sas", "matlab"})
ALLOWED_PROVIDERS = frozenset({"anthropic", "openai"})
